### ISSUE TITLE
Provide an Operator for Dataverse

### ISSUE THREAD

**Issue by pdurbin** [gdcc/dataverse-kubernetes#182]
The current state-of-the art method for handling complex systems like Dataverse on Kubernetes is via the [operator pattern](https://kubernetes.io/docs/concepts/extend-kubernetes/operator).

Also, creating a custom resource descriptor (CRD) is a common way how to deploy components these days. This needs an operator to be understood by Kubernetes.

An operator could use some of the frameworks out there (Operator SDK, ...), but it is very tempting to create a Java-based software for this.

There are a few Java Kubernetes clients that support creating such things, but this might involve some more crafting than relying on the frameworks. Those on the other hand mostly support the Go language only, which is not very common in the Dataverse community.

An operator would need to handle cases like:
- Deploy configuration changes when `ConfigMap`s
- Do updates, trigger reindexes etc, depending on what update you are doing in your installation
- ...

As operators for Postgres and Solr already exist, those should be reused instead of creating our own. Packaging the complete thing as a system can (and should) still be done via tools like helm, kustomize et al. Those should deploy then the new CRDs and Operators instead of the current Deployments etc (those will be done by the controller)

**Comment by poikilotherm** [comment]
This will be done in https://github.com/gdcc/dvopa. Please open issues there.
